# name: Build and Push to ECR

# on:
#   push:
#     branches:
#       - master

# jobs:
#   build-and-push:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Set up AWS credentials
#         uses: aws-actions/configure-aws-credentials@v1
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: ${{ secrets.AWS_REGION }}

#       - name: Log in to Amazon ECR
#         id: login-ecr
#         uses: aws-actions/amazon-ecr-login@v1

#       - name: Build Docker images
#         run: |
#           docker build -t ${{ secrets.ECR_REGISTRY }}/pulsar:latest ./pulsar
#           docker build -t ${{ secrets.ECR_REGISTRY }}/keycloak:latest ./keycloak
#           docker build -t ${{ secrets.ECR_REGISTRY }}/eureka:latest ./eureka

#       - name: Push Docker images
#         run: |
#           docker push ${{ secrets.ECR_REGISTRY }}/pulsar:latest
#           docker push ${{ secrets.ECR_REGISTRY }}/keycloak:latest
#           docker push ${{ secrets.ECR_REGISTRY }}/eureka:latest













name: Build and Push to ECR

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Build and push with Docker Compose
        env:
          ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
        run: |
          echo ${{ secrets.AWS_ACCESS_KEY_ID }} | docker login -u AWS --password-stdin $ECR_REGISTRY
          sed -i 's/image: \([^:]*\):\(.*\)/image: \1:latest/' docker-compose.yml
          docker-compose build
          docker-compose push
